version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - tbs-sites-volume:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - info-sites

volumes:
  tbs-sites-volume:
networks:
  info-sites: